"""activity direction field

Revision ID: 4caad57c75dd
Revises: 82a90f655307
Create Date: 2026-07-20 15:14:09.935130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4caad57c75dd'
down_revision: Union[str, None] = '82a90f655307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('direction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'direction')
    # ### end Alembic commands ###
