"""entity membership table

Revision ID: e16f29475a32
Revises: f3d3590cac78
Create Date: 2026-07-21 07:31:50.753745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e16f29475a32'
down_revision: Union[str, None] = 'f3d3590cac78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_memberships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('added_by', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'user_id', name='uq_entity_membership')
    )
    op.create_index(op.f('ix_entity_memberships_entity_id'), 'entity_memberships', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_memberships_entity_type'), 'entity_memberships', ['entity_type'], unique=False)
    op.create_index('ix_entity_memberships_entity_type_entity_id', 'entity_memberships', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_entity_memberships_entity_type_entity_id', table_name='entity_memberships')
    op.drop_index(op.f('ix_entity_memberships_entity_type'), table_name='entity_memberships')
    op.drop_index(op.f('ix_entity_memberships_entity_id'), table_name='entity_memberships')
    op.drop_table('entity_memberships')
    # ### end Alembic commands ###
