"""deal and project visibility

Revision ID: f3d3590cac78
Revises: 5b9650fc7c8e
Create Date: 2026-07-21 07:12:51.329352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d3590cac78'
down_revision: Union[str, None] = '5b9650fc7c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('visibility', sa.String(), server_default='public', nullable=False))
    op.add_column('projects', sa.Column('visibility', sa.String(), server_default='public', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'visibility')
    op.drop_column('deals', 'visibility')
    # ### end Alembic commands ###
